services:
  - type: web
    name: eventsuganda-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_HOST
        sync: false
      - key: DATABASE_PORT
        value: "5432"
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
